### ISSUE TITLE
Serial Errors on receiving end

### ISSUE THREAD

**Issue by opustecnica** [thephez/data-diode#1]
I have been able to successfully create a setup, but I am having issues with the receiving end.
It seems the py receiver initializes correctly only to engage in an infinite restarting loop.  Any suggestions?

Thank you again for the code and any insight you might have on this issue.

```bash
controls@data-diode-red:~ $ sudo python /opt/sierra/data_diode/transfer_data/serial-recv-file.py
2017-12-10 18:34:37,031 getpid  INFO    PID File /tmp/serial-recv-file.pid written. Process running as PID 954.
2017-12-10 18:34:37,043 getportname     INFO    Linux detected (ARM processor).  Raspberry Pi environment likely.  Defaulting to /dev/ttyAMA0
2017-12-10 18:34:37,046 openserialport  INFO    ------------------------------ Serial Port opened ------------------------------
2017-12-10 18:34:37,048 openserialport  INFO    Serial port opened successfully.
        Port Configuration: Serial<id=0x7689e210, open=True>(port='/dev/ttyAMA0', baudrate=921600, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=0, rtscts=0, dsrdtr=False)
2017-12-10 18:34:37,049 initRTSDTR      DEBUG   Initialize RTS/DTR to Off
2017-12-10 18:34:38,052 main    INFO    ------------------------------ Waiting for file ------------------------------
2017-12-10 18:34:38,059 checkforstring  DEBUG   Waiting for String (<<READY>>)
2017-12-10 18:34:43,067 checkforstring  DEBUG   Waiting for String (<<READY>>),  Received live

2017-12-10 18:34:53,131 main    CRITICAL        Exception in main loop. Restarting...
        Exception Message: [Errno 5] Input/output error
2017-12-10 18:34:54,133 initRTSDTR      DEBUG   Initialize RTS/DTR to Off
2017-12-10 18:34:54,135 main    CRITICAL        Exception in main loop. Restarting...
        Exception Message: [Errno 5] Input/output error
2017-12-10 18:34:55,137 initRTSDTR      DEBUG   Initialize RTS/DTR to Off
2017-12-10 18:34:55,139 main    CRITICAL        Exception in main loop. Restarting...
        Exception Message: [Errno 5] Input/output error
2017-12-10 18:34:56,142 initRTSDTR      DEBUG   Initialize RTS/DTR to Off
2017-12-10 18:34:56,144 main    CRITICAL        Exception in main loop. Restarting...
        Exception Message: [Errno 5] Input/output error
2017-12-10 18:34:57,147 initRTSDTR      DEBUG   Initialize RTS/DTR to Off
2017-12-10 18:34:57,148 main    CRITICAL        Exception in main loop. Restarting...
        Exception Message: [Errno 5] Input/output error
2017-12-10 18:34:58,151 initRTSDTR      DEBUG   Initialize RTS/DTR to Off
2017-12-10 18:34:58,153 main    CRITICAL        Exception in main loop. Restarting...
        Exception Message: [Errno 5] Input/output error
2017-12-10 18:34:59,157 initRTSDTR      DEBUG   Initialize RTS/DTR to Off
2017-12-10 18:34:59,159 main    CRITICAL        Exception in main loop. Restarting...
        Exception Message: [Errno 5] Input/output error
2017-12-10 18:35:00,161 initRTSDTR      DEBUG   Initialize RTS/DTR to Off
2017-12-10 18:35:00,163 main    CRITICAL        Exception in main loop. Restarting...
        Exception Message: [Errno 5] Input/output error
^XTraceback (most recent call last):
  File "/opt/sierra/data_diode/transfer_data/serial-recv-file.py", line 551, in <module>
    main()
  File "/opt/sierra/data_diode/transfer_data/serial-recv-file.py", line 548, in main
    time.sleep(1) # JR
KeyboardInterrupt
2017-12-10 18:35:00,705 initRTSDTR      DEBUG   Initialize RTS/DTR to Off
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/sierra/data_diode/transfer_data/serial-recv-file.py", line 443, in closeserialport
    initRTSDTR(connection)
  File "/opt/sierra/data_diode/transfer_data/serial-recv-file.py", line 160, in initRTSDTR
    connection.setDTR(0)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 599, in setDTR
    self.dtr = value
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 469, in dtr
    self._update_dtr_state()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 636, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIC, TIOCM_DTR_str)
IOError: [Errno 5] Input/output error
Exiting and removing PID file /tmp/serial-recv-file.pid (PID #954)
2017-12-10 18:35:00,716 removepid       INFO    Exiting and removing PID file /tmp/serial-recv-file.pid (PID #954)
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/sierra/data_diode/transfer_data/serial-recv-file.py", line 443, in closeserialport
    initRTSDTR(connection)
  File "/opt/sierra/data_diode/transfer_data/serial-recv-file.py", line 160, in initRTSDTR
    connection.setDTR(0)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 599, in setDTR
    self.dtr = value
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 469, in dtr
    self._update_dtr_state()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 636, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIC, TIOCM_DTR_str)
IOError: [Errno 5] Input/output error
```

**Comment by thephez** [comment]
@opustecnica It has been about a year and a half since I last used this and unfortunately do not have the hardware to set up myself anymore. The infinite loop behavior is semi-intended.  I always wanted it to restart in the event of a failure.  Although that should be a rare event unlike what you are seeing.  A couple thoughts that may or may not help:

1. I was using a Raspberry Pi 2 with the version of Raspbian that was current about 2 years ago.  There could be some compatibility issues if you are using a newer model of Pi / OS version / python version.  

2. It appears that you are receiving part of a message from the sending side correctly. This is indicated by the debug line `2017-12-10 18:34:43,067 checkforstring  DEBUG   Waiting for String (<<READY>>),  Received live` - specifically the "Received live" part.  That is coming from [this line of code](https://github.com/thephez/data-diode/blob/master/transfer_data/serial-recv-file.py#L197).  It appears that you are getting the 'live' part of the 'Server Alive' message sent by the other end (defined [here](https://github.com/thephez/data-diode/blob/master/transfer_data/serial-send-file.py#L24) and sent [here](https://github.com/thephez/data-diode/blob/master/transfer_data/serial-send-file.py#L457)). I would double check the baud rate settings on both sides - they probably are correct, but will definitely cause issues if they do not match.

3. Some of the traceback messages go back into the `serial` package (https://pythonhosted.org/pyserial/). It is possible its functionality has changed a bit since I was working with it and that is causing some issues.  You may need to follow that logic back a bit.

4. You might try adding some debugging/logging to [this else statement](https://github.com/thephez/data-diode/blob/master/transfer_data/serial-recv-file.py#L202) which is likely being entered.

I will let you know if I think of anything else.  If you come up with any new info, let me know too and I will see if I can assist more.

One final question - does it fail in the same way every time (i.e. after approximately the same amount of time, with the same sequence of debug messages, etc.)?

**Comment by opustecnica** [comment]
First off, thank you for diving back into it 1.5 years later :-)
In order to replicate, to the extent possible, the setup you had when the code was conceived, I have used 2 RPI 2 and the jessie version of Raspbian lite.  During installation there were a few issues with Python, but nothing that a few extra steps could not resolve.
I will begin debugging per you suggestions above, yet I have a gut feeling the issue is related to either a missing location to write to or mismatched rights on the receiving directory.  
I will let you know what I discover.

Thank you again.

**Comment by thephez** [comment]
You may want to manually verify that the serial connections between the devices is working as expected (the RTS/DTR and CTS/DSR lines).  For example, run a terminal application on the receiving side, watch what is being received, and manually toggle the lines (per the [defined protocol](https://github.com/thephez/data-diode/blob/master/transfer_data/serial-send-file.py#L387)). That should give you some good info to go on regarding the communication.

It is possible that a permission issue is causing an exception; however, the debug log shown does not even get as far as receiving the filename from the receiving side. If it is a permission issue that early in the process, it may be related to failing to write the debug log data to disk.  Check the paths for the various output directories including https://github.com/thephez/data-diode/blob/master/transfer_data/serial-recv-file.py#L18 and https://github.com/thephez/data-diode/blob/master/transfer_data/serial-recv-file.py#L30-L31.

**Comment by opustecnica** [comment]
Well, thank you!
Using screen and a couple of utilities allowed me to verify that that was a serial misconfiguration on  the receiving end.  The funny part is that that was exactly your first hint.  Lesson learned: check, check and than check again.
Next step is to see how this behaves in the RPI3.  The UART controls are shared with the bluetooth control and this deserves some more reading.  I think I will approach it progressively:
1) RPI3 and jessie
2) Verify and correct for serial differences
3) RPI3 and stretch

I will keep you posted on progress.

PS To some degree and for the type of application, the RPI3 with its WiFi and BT is not exactly the right HW target as those offer a potential point of data access.

**Comment by thephez** [comment]
Glad it worked out.  I will close the issue now.
